name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
outputs:
  version: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
